### ISSUE TITLE
DSX Desktop (with RStudio) -- Persistent Spinning Circle

### ISSUE THREAD

**Issue by cgoo4** [IBMDataScience/DSx-Desktop#56] opened 2018-03-11 08:22 UTC
I downloaded DSX Version 1.2.2 (2/20/2018) to a Windows 7 machine (ticking RStudio).  RStudio initially worked, but opening DSX the next day, I just got a persistent spinning circle.

I uninstalled yesterday, and re-installed. RStudio worked fine for the rest of the day. Opening DSX just after midnight, and again today, I am getting the persistent spinning circle again.
[dsx-desktop.log](https://github.com/IBMDataScience/DSx-Desktop/files/1800138/dsx-desktop.log)

**Comment by cgoo4** [comment] 2018-03-14 09:11
Further update: As I wanted to try something in RStudio yesterday, I did a 3rd fresh install. The install only completes successfully if I temporarily disable the firewall. And RStudio again operated okay for the day, but trying to open again this morning, I get the persistent spinning circle.

**Comment by jerry1100** [comment] 2018-04-17 18:30
Hi @cgoo4, this line from your logs:
```
[2018-03-11 08:06:18:0293] [error] exec error: Error: Command failed: docker-machine env
--shell cmd ibm-dsx
Error checking TLS connection: Error checking and/or regenerating the certs: There was an
error validating certificates for host "192.168.99.102:2376": dial tcp
192.168.99.102:2376: i/o timeout
```
seems to indicate a problem with regenerating the certs.

You mentioned that you had to disable your firewall to complete the install. Were you able to launch RStudio when your firewall was up?

Also, if you're able to reproduce the issue, I'd like to discuss to see if we can figure out why this is happening, since I'm not sure what's causing it.

**Comment by cgoo4** [comment] 2018-04-20 16:04
Jerry hi - It did work a couple of times when "Running as Administrator".  Should that be necessary? Will try again when #64 is resolved as I currently don't have a successfully installed version.

**Comment by jerry1100** [comment] 2018-04-26 17:52
After reading #64, I don't think this is an issue with rstudio, but rather with the docker machine not being able to start properly. That said, let's close this and continue our conversation in #64.

**Closed by jerry1100** 2018-04-26 17:52 UTC
